server:
  contextPath: /api
  servlet:
    context-path: /ms/scheduler
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: scheduler-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:h2:mem:scheduleDB
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      use_sql_comments: false
      format_sql: false
logging:
  level:
    org:
      hibernate:
        SQL: info
